# Generated by Django 4.0.6 on 2023-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_user2_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('emailID', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=1000)),
                ('age', models.EmailField(max_length=20)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.EmailField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('height', models.EmailField(max_length=100)),
                ('bloodgroup', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user2',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
