# Generated by Django 4.0.6 on 2023-04-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_medicsuser_alter_user2_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicsuser',
            name='phoneNo',
            field=models.CharField(default=9876543210, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicsuser',
            name='age',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicsuser',
            name='dob',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicsuser',
            name='height',
            field=models.CharField(max_length=100),
        ),
    ]
